openapi: 3.1.0
info:
  title: Delete Sub-Tenant
  version: 1.0.0
paths:
  /delete_sub_tenant:
    delete:
      summary: Delete Sub-Tenant
      description: >
        Delete a specific sub-tenant from a given tenant. This endpoint validates that the sub-tenant 
        is not the primary/default sub-tenant before deletion.
      parameters:
        - name: Authorization
          in: header
          required: true
          description: Bearer token (your API key)
          schema:
            type: string
          example: "Bearer {API_KEY}"
        - name: accept
          in: header
          required: true
          description: Response content type
          schema:
            type: string
            default: application/json
        - name: tenant_id
          in: query
          required: true
          description: The primary tenant identifier
          schema:
            type: string
          example: "acme_corp"
        - name: sub_tenant_id
          in: query
          required: true
          description: The sub-tenant identifier to delete
          schema:
            type: string
          example: "engineering"
      responses:
        '200':
          description: Sub-tenant deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Status of the deletion operation
                    example: "success"
                  tenant_id:
                    type: string
                    description: The tenant identifier
                    example: "acme_corp"
                  sub_tenant_id:
                    type: string
                    description: The deleted sub-tenant identifier
                    example: "engineering"
                  message:
                    type: string
                    description: Human-readable message about the operation
                    example: "Sub-tenant 'engineering' deleted successfully from tenant 'acme_corp'"
              example:
                status: "success"
                tenant_id: "acme_corp"
                sub_tenant_id: "engineering"
                message: "Sub-tenant 'engineering' deleted successfully from tenant 'acme_corp'"
        '400':
          description: Bad request - Cannot delete default sub-tenant
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: false
                  message:
                    type: string
                    example: "Cannot delete the default sub-tenant"
                  data:
                    type: "null"
                    example: null
                  error_code:
                    type: string
                    example: "CANNOT_DELETE_DEFAULT_SUB_TENANT"
        '401':
          description: Invalid or missing API key
        '404':
          description: Tenant or sub-tenant not found
        '5XX':
          description: Internal server error