openapi: 3.1.0
info:
  title: Create Embeddings Tenant
  version: 1.0.0
paths:
  /embeddings/create_embeddings_tenant:
    post:
      summary: Create Embeddings Tenant
      description: >
        Creates an embeddings-only tenant. Use this for direct embeddings upload and search workflows.
      parameters:
        - name: Authorization
          in: header
          required: true
          description: Bearer token (your API key)
          schema:
            type: string
          example: "Bearer {API_KEY}"
        - name: accept
          in: header
          required: true
          description: Response content type
          schema:
            type: string
            default: application/json
        - name: tenant_id
          in: query
          required: true
          description: The tenant identifier.
          schema:
            type: string
          example: "embeddings_test"
      responses:
        '200':
          description: Embeddings tenant created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  message:
                    type: string
                    example: "Tenant 'embeddings_test' created successfully."
                  tenant_id:
                    type: string
                    description: The created tenant identifier
                    example: "embeddings_test"
                required:
                  - status
                  - message
                  - tenant_id
              example:
                status: "success"
                message: "Tenant 'embeddings_test' created successfully."
                tenant_id: "embeddings_test"
        '401':
          description: Invalid or missing API key
        '409':
          description: Tenant already exists
        '5XX':
          description: Internal server error
